### ISSUE TITLE
Ненужный разделитель перед описанием возвышений

### ISSUE THREAD

**Issue by Laritello** [Laritello/pf-card-generator#18]
### Описание проблемы
Описание вмещается на страницу, а первый пункт описания возвышения - уже нет. В таком случае, разделитель всё-равно отображается.
![image](https://github.com/Laritello/pf-card-generator/assets/29901577/8d6861d7-8fe1-4ffd-a3a9-b2c67b056cd8)

### Решение
Отслеживать, если перенос начинается с первой строки возвышений. Если условие выполняется - прятать разделитель.
### Пример карт с данной проблемой
ВПИТЫВАНИЕ СТИХИИ, ВРЕДНЫЙ ПОЛТЕРГЕЙСТ, ПОСВЯЩЕНИЕ, ПОТОК ВНУТРЕННЕГО СВЕЧЕНИЯ, СТЕНА ЛЬДА, ПОВЫШЕНИЕ ШАНСОВ

**Comment by AlexPutin** [comment]
Вроде бы пофиксил, но нужно тестирование

**Comment by AlexPutin** [comment]
@Laritello потести, вроде починил

**Comment by Laritello** [comment]
@AlexYukikaze ошибок не увидел, по списку проверил - линия убрана. Всё ок.
