### ISSUE TITLE
Фокусные заклинания

### ISSUE THREAD

**Issue by sangeet79** [Laritello/pf-card-generator#23]
Прежде чем создать это issue, раз 10 перепроверил на всякий случай. Не подтягиваниются фокусные заклинания. Если выбрать в фильтре "Фокусные", отображается пустой лист, через индивидуальные фильтры тоже ничего найти нельзя.

**Comment by Laritello** [comment]
Да, так и есть. Мы их тогда в UI добавили, но не добавили в данные.
@AlexYukikaze мы так фокусы тогда и не добавили. Как время будет сможешь добавить их в spells.json, если у тебя скрипт остался?

**Comment by AlexPutin** [comment]
Сграбил файлы, на днях гляну, что с ними можно сделать

**Comment by sangeet79** [comment]
а раз уж зашёл разговор о вытягивании данных, может за одно рассмотрите возможность добавления алхимических формул? :) карточки спеллов прекрасны, у меня всем зашло на ура, но алхимик почти рыдает :)

**Comment by AlexPutin** [comment]
Добавил, пока в тестовом режиме, без фильтров по классам/доменам/родословным и т.д.

**Comment by AlexPutin** [comment]
![image](https://github.com/Laritello/pf-card-generator/assets/2861110/8b304d46-f5e7-422b-bf34-d860d267ac1a)
Добавили вкладку с фокусами, добавили фильтрацию по архетипам и уровням фокусов
